* nvim
** how to install a plugin
The easiest way is to install a plugin manager. I personally use
[[https://github.com/junegunn/vim-plug][vim-plug]] by /Junegunn/.
To install it, simply run
#+begin_src sh
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
#+end_src
Then, in your =~/.config/nvim/init.vim=:
#+begin_src vim
call plug#begin('~/.config/nvim/plugged')
      Plug 'morhetz/gruvbox'
call plug#end()
#+end_src
Relaod your =init.vim= and =:PlugInstall= to install plugins.

** how to have auto completion
There are so many auto completion engines for 
neovim. However, I really like 
[[https://github.com/neoclide/coc.nvim][coc]] from neoclide. First, you need to have =nodejs=
version >= 12.12.
#+begin_src sh
sudo pacman -S nodejs
#+end_src
And in your =init.vim= (for =vim-plug=) user:
#+begin_src vim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
#+end_src
Then you have to install coc extension or configure language servers for LSP support.
Installing a language server by
=:CocInstall coc-vimtex=.
* LaTeX
** how to install latex on linux
For Linux user's, I recommend using [[https://tug.org/texlive/][texlive]].
You can use any text editors that you like, 
for beginners, it's best to use [[https://www.xm1math.net/texmaker/][texmaker]].
To install, run the following:
#+begin_src sh
sudo pacan -S texlive-most texlive-lang biber texmaker
#+end_src
for more info, see [[https://wiki.archlinux.org/title/TeX_Live][arch wiki]].
